include:
  - 'https://colisweb-idl.gitlab.io/colisweb-open-source/ci-common/v14.0.0/templates/scala.yml'

compile:
  extends: .sbt-compile
  tags: []

unused-dependencies:
  extends: .sbt-unused-dependencies
  tags: []

version:
  extends: .version
  tags: []

publish on sonatype:
  extends: .sonatype-publish
  tags: []

